name: Acceptance-Testing-Selenium

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.13", "3.12", "3.11" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest behave selenium

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          sudo apt-get install -y chromium-chromedriver
          sudo ln -s /usr/bin/chromedriver /usr/local/bin/chromedriver

      - name: Run pytest (unit tests)
        run: |
          pytest tests/unit --maxfail=1 --disable-warnings -q

      - name: Run Behave (acceptance tests)
        run: |
          behave tests/acceptance